INSERT INTO specializzazioni (spec) VALUES ('Medico di Base');
INSERT INTO specializzazioni (spec) VALUES ('Allergologia');
INSERT INTO specializzazioni (spec) VALUES ('Anestesiologia');
INSERT INTO specializzazioni (spec) VALUES ('Angiologia');
INSERT INTO specializzazioni (spec) VALUES ('Audiologia');
INSERT INTO specializzazioni (spec) VALUES ('Cardiochirurgia');
INSERT INTO specializzazioni (spec) VALUES ('Cardiologia');
INSERT INTO specializzazioni (spec) VALUES ('Chirurgia');
INSERT INTO specializzazioni (spec) VALUES ('Odontoiatria');
INSERT INTO specializzazioni (spec) VALUES ('Dermatologia');
INSERT INTO specializzazioni (spec) VALUES ('Medicina Estetica');
INSERT INTO specializzazioni (spec) VALUES ('Medicina Fisica');
INSERT INTO specializzazioni (spec) VALUES ('Medicina Nucleare');
INSERT INTO specializzazioni (spec) VALUES ('Radiologia');
INSERT INTO specializzazioni (spec) VALUES ('Neurologia');
INSERT INTO specializzazioni (spec) VALUES ('Dietologia');
INSERT INTO specializzazioni (spec) VALUES ('Ematologia');
INSERT INTO specializzazioni (spec) VALUES ('Endocrinologia');
INSERT INTO specializzazioni (spec) VALUES ('Epatologia');
INSERT INTO specializzazioni (spec) VALUES ('Fisiatria');
INSERT INTO specializzazioni (spec) VALUES ('Gastroenterologia');
INSERT INTO specializzazioni (spec) VALUES ('Gerontologia');
INSERT INTO specializzazioni (spec) VALUES ('Ginecologia');
INSERT INTO specializzazioni (spec) VALUES ('Immunologia');
INSERT INTO specializzazioni (spec) VALUES ('Infettivologia');
INSERT INTO specializzazioni (spec) VALUES ('Nefrologia');
INSERT INTO specializzazioni (spec) VALUES ('Neurochirurgia');
INSERT INTO specializzazioni (spec) VALUES ('Neuropsichiatria');
INSERT INTO specializzazioni (spec) VALUES ('Oftamologia');
INSERT INTO specializzazioni (spec) VALUES ('Oncoematologia');
INSERT INTO specializzazioni (spec) VALUES ('Oncologia');
INSERT INTO specializzazioni (spec) VALUES ('Ortopedia');
INSERT INTO specializzazioni (spec) VALUES ('Ostetricia');
INSERT INTO specializzazioni (spec) VALUES ('Otorinolaringoiatria');
INSERT INTO specializzazioni (spec) VALUES ('Pediatria');
INSERT INTO specializzazioni (spec) VALUES ('Pneumologia');
INSERT INTO specializzazioni (spec) VALUES ('Proctologia');
INSERT INTO specializzazioni (spec) VALUES ('Psichiatria');
INSERT INTO specializzazioni (spec) VALUES ('Reumatologia');
INSERT INTO specializzazioni (spec) VALUES ('Senologia');
INSERT INTO specializzazioni (spec) VALUES ('Urologia');
