INSERT INTO tipi_visita (nome, costo, spec_id) VALUES ('Visita allergologica', 50, 1);
INSERT INTO tipi_visita (nome, costo, spec_id) VALUES ('Visita allergologica di controllo', 50, 1);
INSERT INTO tipi_visita (nome, costo, spec_id) VALUES ('Visita anestesiologica/algologica', 50, 2);
INSERT INTO tipi_visita (nome, costo, spec_id) VALUES ('Visita anestesiologica/algologica di controllo', 50, 2);
INSERT INTO tipi_visita (nome, costo, spec_id) VALUES ('Visita angiologica', 50, 3);
INSERT INTO tipi_visita (nome, costo, spec_id) VALUES ('Visita angiologica di controllo', 50, 3);
INSERT INTO tipi_visita (nome, costo, spec_id) VALUES ('Visita audiologica', 50, 4);
INSERT INTO tipi_visita (nome, costo, spec_id) VALUES ('Visita foniatrica', 50, 4);
INSERT INTO tipi_visita (nome, costo, spec_id) VALUES ('Visita cardiochirurgica', 50, 5);
INSERT INTO tipi_visita (nome, costo, spec_id) VALUES ('Visita cardiochirurgica di controllo', 50, 5);
INSERT INTO tipi_visita (nome, costo, spec_id) VALUES ('Visita cardiochirurgica pediatrica', 50, 5);
INSERT INTO tipi_visita (nome, costo, spec_id) VALUES ('Visita cardiochirurgica pediatrica di controllo', 50, 5);
INSERT INTO tipi_visita (nome, costo, spec_id) VALUES ('Visita cardiologica di controllo', 50, 6);
INSERT INTO tipi_visita (nome, costo, spec_id) VALUES ('Visita cardiologica. Incluso: ECG', 50, 6);
INSERT INTO tipi_visita (nome, costo, spec_id) VALUES ('Visita chirurgia di controllo', 50, 7);
INSERT INTO tipi_visita (nome, costo, spec_id) VALUES ('Visita chirurgia generale', 50, 7);
INSERT INTO tipi_visita (nome, costo, spec_id) VALUES ('Visita chirurgia maxillo facciale', 50, 7);
INSERT INTO tipi_visita (nome, costo, spec_id) VALUES ('Visita chirurgia maxillo facciale di controllo', 50, 7);
INSERT INTO tipi_visita (nome, costo, spec_id) VALUES ('Visita chirurgia pediatrica', 50, 7);
INSERT INTO tipi_visita (nome, costo, spec_id) VALUES ('Visita chirurgia pediatrica di controllo', 50, 7);
INSERT INTO tipi_visita (nome, costo, spec_id) VALUES ('Visita chirurgia plastica', 50, 7);
INSERT INTO tipi_visita (nome, costo, spec_id) VALUES ('Visita chirurgia plastica di controllo', 50, 7);
INSERT INTO tipi_visita (nome, costo, spec_id) VALUES ('Visita chirurgia toracica', 50, 7);
INSERT INTO tipi_visita (nome, costo, spec_id) VALUES ('Visita chirurgia toracica di controllo', 50, 7);
INSERT INTO tipi_visita (nome, costo, spec_id) VALUES ('Visita chirurgia vascolare', 50, 7);
INSERT INTO tipi_visita (nome, costo, spec_id) VALUES ('Visita chirurgia vascolare di controllo', 50, 7);
INSERT INTO tipi_visita (nome, costo, spec_id) VALUES ('Visita dentistica - odontostomatologica', 50, 8);
INSERT INTO tipi_visita (nome, costo, spec_id) VALUES ('Visita dentistica - odontostomatologica di controllo', 50, 8);
INSERT INTO tipi_visita (nome, costo, spec_id) VALUES ('Visita dentistica - odontostomatologica pediatrica', 50, 8);
INSERT INTO tipi_visita (nome, costo, spec_id) VALUES ('Visita dermatologica', 50, 9);
INSERT INTO tipi_visita (nome, costo, spec_id) VALUES ('Visita dermatologica di controllo', 50, 9);
INSERT INTO tipi_visita (nome, costo, spec_id) VALUES ('Visita di medicina estetica', 50, 10);
INSERT INTO tipi_visita (nome, costo, spec_id) VALUES ('Visita di medicina estetica di controllo', 50, 10);
INSERT INTO tipi_visita (nome, costo, spec_id) VALUES ('Visita di medicina fisica e riabilitazione', 50, 11);
INSERT INTO tipi_visita (nome, costo, spec_id) VALUES ('Visita di medicina fisica e riabilitazione di controllo', 50, 11);
INSERT INTO tipi_visita (nome, costo, spec_id) VALUES ('Visita di medicina nucleare', 50, 12);
INSERT INTO tipi_visita (nome, costo, spec_id) VALUES ('Visita di medicina nucleare di controllo', 50, 12);
INSERT INTO tipi_visita (nome, costo, spec_id) VALUES ('Visita di radiologia interventistica', 50, 13);
INSERT INTO tipi_visita (nome, costo, spec_id) VALUES ('Visita di radiologia interventistica di controllo', 50, 13);
INSERT INTO tipi_visita (nome, costo, spec_id) VALUES ('Visita di radioterapia', 50, 13);
INSERT INTO tipi_visita (nome, costo, spec_id) VALUES ('Visita di riabilitazione neurologica', 50, 14);
INSERT INTO tipi_visita (nome, costo, spec_id) VALUES ('Visita di riabilitazione neurologica di controllo', 50, 14);
INSERT INTO tipi_visita (nome, costo, spec_id) VALUES ('Visita dietologica', 50, 15);
INSERT INTO tipi_visita (nome, costo, spec_id) VALUES ('Visita dietologica di controllo', 50, 15);
INSERT INTO tipi_visita (nome, costo, spec_id) VALUES ('Visita ematologica', 50, 16);
INSERT INTO tipi_visita (nome, costo, spec_id) VALUES ('Visita ematologica di controllo', 50, 16);
INSERT INTO tipi_visita (nome, costo, spec_id) VALUES ('Visita endocrinologica e diabetologica', 50, 17);
INSERT INTO tipi_visita (nome, costo, spec_id) VALUES ('Visita endocrinologica e diabetologica di controllo', 50, 17);
INSERT INTO tipi_visita (nome, costo, spec_id) VALUES ('Visita endocrinologica pediatrica', 50, 17);
INSERT INTO tipi_visita (nome, costo, spec_id) VALUES ('Visita epatologica', 50, 18);
INSERT INTO tipi_visita (nome, costo, spec_id) VALUES ('Visita epatologica di controllo', 50, 18);
INSERT INTO tipi_visita (nome, costo, spec_id) VALUES ('Visita fisiatrica', 50, 19);
INSERT INTO tipi_visita (nome, costo, spec_id) VALUES ('Visita fisiatrica di controllo', 50, 19);
INSERT INTO tipi_visita (nome, costo, spec_id) VALUES ('Visita gastroenterologica', 50, 20);
INSERT INTO tipi_visita (nome, costo, spec_id) VALUES ('Visita gastroenterologica di controllo', 50, 20);
INSERT INTO tipi_visita (nome, costo, spec_id) VALUES ('Visita geriatrica', 50, 21);
INSERT INTO tipi_visita (nome, costo, spec_id) VALUES ('Visita geriatrica di controllo', 50, 21);
INSERT INTO tipi_visita (nome, costo, spec_id) VALUES ('Visita ginecologica', 50, 22);
INSERT INTO tipi_visita (nome, costo, spec_id) VALUES ('Visita ginecologica di controllo', 50, 22);
INSERT INTO tipi_visita (nome, costo, spec_id) VALUES ('Visita immunologica', 50, 23);
INSERT INTO tipi_visita (nome, costo, spec_id) VALUES ('Visita Immunologica di controllo', 50, 23);
INSERT INTO tipi_visita (nome, costo, spec_id) VALUES ('Visita infettivologica o delle malattie tropicali', 50, 24);
INSERT INTO tipi_visita (nome, costo, spec_id) VALUES ('Visita infettivologica o delle malattie tropicali di controllo', 50, 24);
INSERT INTO tipi_visita (nome, costo, spec_id) VALUES ('Visita nefrologica', 50, 25);
INSERT INTO tipi_visita (nome, costo, spec_id) VALUES ('Visita nefrologica di controllo', 50, 25);
INSERT INTO tipi_visita (nome, costo, spec_id) VALUES ('Visita nefrologica pediatrica', 50, 25);
INSERT INTO tipi_visita (nome, costo, spec_id) VALUES ('Visita nefrologica pediatrica di controllo', 50, 25);
INSERT INTO tipi_visita (nome, costo, spec_id) VALUES ('Visita neurochirurgica', 50, 26);
INSERT INTO tipi_visita (nome, costo, spec_id) VALUES ('Visita neurochirurgica di controllo', 50, 26);
INSERT INTO tipi_visita (nome, costo, spec_id) VALUES ('Visita neurochirurgica pediatrica', 50, 26);
INSERT INTO tipi_visita (nome, costo, spec_id) VALUES ('Visita neurologica', 50, 14);
INSERT INTO tipi_visita (nome, costo, spec_id) VALUES ('Visita neurologica di controllo', 50, 14);
INSERT INTO tipi_visita (nome, costo, spec_id) VALUES ('Visita neurologica pediatrica', 50, 14);
INSERT INTO tipi_visita (nome, costo, spec_id) VALUES ('Visita neuropsichiatrica infantile', 50, 27);
INSERT INTO tipi_visita (nome, costo, spec_id) VALUES ('Visita neuropsichiatrica infantile di controllo', 50, 27);
INSERT INTO tipi_visita (nome, costo, spec_id) VALUES ('Visita oculistica', 50, 28);
INSERT INTO tipi_visita (nome, costo, spec_id) VALUES ('Visita oculistica di controllo', 50, 28);
INSERT INTO tipi_visita (nome, costo, spec_id) VALUES ('Visita oculistica pediatrica', 50, 28);
INSERT INTO tipi_visita (nome, costo, spec_id) VALUES ('Visita oncoematologica', 50, 29);
INSERT INTO tipi_visita (nome, costo, spec_id) VALUES ('Visita oncoematologica di controllo', 50, 29);
INSERT INTO tipi_visita (nome, costo, spec_id) VALUES ('Visita oncoematologica pediatrica', 50, 29);
INSERT INTO tipi_visita (nome, costo, spec_id) VALUES ('Visita oncoematologica pediatrica di controllo', 50, 29);
INSERT INTO tipi_visita (nome, costo, spec_id) VALUES ('Visita oncologica', 50, 30);
INSERT INTO tipi_visita (nome, costo, spec_id) VALUES ('Visita oncologica di controllo', 50, 30);
INSERT INTO tipi_visita (nome, costo, spec_id) VALUES ('Visita ortopedica', 50, 31);
INSERT INTO tipi_visita (nome, costo, spec_id) VALUES ('Visita ortopedica di controllo', 50, 31);
INSERT INTO tipi_visita (nome, costo, spec_id) VALUES ('Visita ostetrica', 50, 32);
INSERT INTO tipi_visita (nome, costo, spec_id) VALUES ('Visita ostetrica di controllo', 50, 32);
INSERT INTO tipi_visita (nome, costo, spec_id) VALUES ('Visita otorinolaringoiatrica', 50, 33);
INSERT INTO tipi_visita (nome, costo, spec_id) VALUES ('Visita otorinolaringoiatrica di controllo', 50, 33);
INSERT INTO tipi_visita (nome, costo, spec_id) VALUES ('Visita pediatrica', 50, 34);
INSERT INTO tipi_visita (nome, costo, spec_id) VALUES ('Visita pneumologica', 50, 35);
INSERT INTO tipi_visita (nome, costo, spec_id) VALUES ('Visita pneumologica di controllo', 50, 35);
INSERT INTO tipi_visita (nome, costo, spec_id) VALUES ('Visita proctologica', 50, 36);
INSERT INTO tipi_visita (nome, costo, spec_id) VALUES ('Visita proctologica di controllo', 50, 36);
INSERT INTO tipi_visita (nome, costo, spec_id) VALUES ('Visita psichiatrica', 50, 37);
INSERT INTO tipi_visita (nome, costo, spec_id) VALUES ('Visita psichiatrica di controllo', 50, 37);
INSERT INTO tipi_visita (nome, costo, spec_id) VALUES ('Visita psicodiagnostica', 50, 37);
INSERT INTO tipi_visita (nome, costo, spec_id) VALUES ('Visita reumatologica', 50, 38);
INSERT INTO tipi_visita (nome, costo, spec_id) VALUES ('Visita reumatologica di controllo', 50, 38);
INSERT INTO tipi_visita (nome, costo, spec_id) VALUES ('Visita senologica', 50, 39);
INSERT INTO tipi_visita (nome, costo, spec_id) VALUES ('Visita senologica di controllo', 50, 39);
INSERT INTO tipi_visita (nome, costo, spec_id) VALUES ('Visita urologica pediatrica', 50, 40);
INSERT INTO tipi_visita (nome, costo, spec_id) VALUES ('Visita urologica pediatrica di controllo', 50, 40);
INSERT INTO tipi_visita (nome, costo, spec_id) VALUES ('Visita urologica/andrologica', 50, 40);
INSERT INTO tipi_visita (nome, costo, spec_id) VALUES ('Visita urologica/andrologica di controllo', 50, 40);