INSERT INTO tipi_esame (nome, costo) VALUES('Deossicortisolo', 11);
INSERT INTO tipi_esame (nome, costo) VALUES('Acido 5 idrossi 3 indolacetico', 11);
INSERT INTO tipi_esame (nome, costo) VALUES('Acido delta', 11);
INSERT INTO tipi_esame (nome, costo) VALUES('Ala deidrasi', 11);
INSERT INTO tipi_esame (nome, costo) VALUES('Alanina', 11);
INSERT INTO tipi_esame (nome, costo) VALUES('Albumina', 11);
INSERT INTO tipi_esame (nome, costo) VALUES('Aldolasi', 11);
INSERT INTO tipi_esame (nome, costo) VALUES('Alfa amilasi', 11);
INSERT INTO tipi_esame (nome, costo) VALUES('Alfa amilasi isoenzimi', 11);
INSERT INTO tipi_esame (nome, costo) VALUES('Androstenediolo', 11);
INSERT INTO tipi_esame (nome, costo) VALUES('Aspartato aminotrasferiasi', 11);
INSERT INTO tipi_esame (nome, costo) VALUES('Calcio totale', 11);
INSERT INTO tipi_esame (nome, costo) VALUES('Colesterolo HDL', 11);
INSERT INTO tipi_esame (nome, costo) VALUES('Colesterolo LDL', 11);
INSERT INTO tipi_esame (nome, costo) VALUES('Colesterolo totale', 11);
INSERT INTO tipi_esame (nome, costo) VALUES('Creatinchinasi', 11);
INSERT INTO tipi_esame (nome, costo) VALUES('Creatinina', 11);
INSERT INTO tipi_esame (nome, costo) VALUES('Cromo', 11);
INSERT INTO tipi_esame (nome, costo) VALUES('Enolasi', 11);
INSERT INTO tipi_esame (nome, costo) VALUES('Ferro', 11);
INSERT INTO tipi_esame (nome, costo) VALUES('Fosfatasi acida', 11);
INSERT INTO tipi_esame (nome, costo) VALUES('Fosfatasi alcalina', 11);
INSERT INTO tipi_esame (nome, costo) VALUES('Fosfatasi alcalina isoenzima osseo', 11);
INSERT INTO tipi_esame (nome, costo) VALUES('Fosfato inorganico', 11);
INSERT INTO tipi_esame (nome, costo) VALUES('Lattato', 11);
INSERT INTO tipi_esame (nome, costo) VALUES('lipasi', 11);
INSERT INTO tipi_esame (nome, costo) VALUES('Magnesio', 11);
INSERT INTO tipi_esame (nome, costo) VALUES('Mioglobina', 11);
INSERT INTO tipi_esame (nome, costo) VALUES('Potassio', 11);
INSERT INTO tipi_esame (nome, costo) VALUES('Proteine', 11);
INSERT INTO tipi_esame (nome, costo) VALUES('Sodio', 11);
INSERT INTO tipi_esame (nome, costo) VALUES('Sudore', 11);
INSERT INTO tipi_esame (nome, costo) VALUES('Trigliceridi', 11);
INSERT INTO tipi_esame (nome, costo) VALUES('Urato Urea', 11);
INSERT INTO tipi_esame (nome, costo) VALUES('Alfa 2', 11);
INSERT INTO tipi_esame (nome, costo) VALUES('Anticorpi anti microsomi', 11);
INSERT INTO tipi_esame (nome, costo) VALUES('Antigene carboidratico 125', 11);
INSERT INTO tipi_esame (nome, costo) VALUES('Antigene carboidratico15.3', 11);
INSERT INTO tipi_esame (nome, costo) VALUES('Antigene carboidratico 19.9', 11);
INSERT INTO tipi_esame (nome, costo) VALUES('Antigene carcino embrionario', 11);
INSERT INTO tipi_esame (nome, costo) VALUES('Antigeni HLA', 11);
INSERT INTO tipi_esame (nome, costo) VALUES('beta tromboglobulina', 11);
INSERT INTO tipi_esame (nome, costo) VALUES('cyfra', 11);
INSERT INTO tipi_esame (nome, costo) VALUES('Eparina', 11);
INSERT INTO tipi_esame (nome, costo) VALUES('Fenotipo RH', 11);
INSERT INTO tipi_esame (nome, costo) VALUES('Glicoproteina', 11);
INSERT INTO tipi_esame (nome, costo) VALUES('Gruppo sanguigno ABO e RH (D)', 11);
INSERT INTO tipi_esame (nome, costo) VALUES('Ige specifiche allergologiche', 11);
INSERT INTO tipi_esame (nome, costo) VALUES('Ige specifiche allergologiche screening qualitativo', 11);
INSERT INTO tipi_esame (nome, costo) VALUES('Ige specifiche allergologiche', 11);
INSERT INTO tipi_esame (nome, costo) VALUES('inibitore attivatore del plasminogeno', 11);
INSERT INTO tipi_esame (nome, costo) VALUES('Tempo di protrombina', 11);
INSERT INTO tipi_esame (nome, costo) VALUES('Tempo di tromboplastina', 11);
INSERT INTO tipi_esame (nome, costo) VALUES('Test aggregazione piastrinica', 11);
INSERT INTO tipi_esame (nome, costo) VALUES('Test resistenza proteina C', 11);
INSERT INTO tipi_esame (nome, costo) VALUES('Tipizzazione genomica', 11);
INSERT INTO tipi_esame (nome, costo) VALUES('Tipizzazione genomica HLA – A sequenziamento diretto', 11);
INSERT INTO tipi_esame (nome, costo) VALUES('Tipizzazione genomica HLA – B', 11);
INSERT INTO tipi_esame (nome, costo) VALUES('Tipizzazione genomica HLA – B sequenziamento diretto', 11);
INSERT INTO tipi_esame (nome, costo) VALUES('Tipizzazione genomica HLA – C', 11);
INSERT INTO tipi_esame (nome, costo) VALUES('Tipizzazione genomica HLA – C seq. diretto', 11);
INSERT INTO tipi_esame (nome, costo) VALUES('Tipizzazione genomica HLA – DP seq. diretto', 11);
INSERT INTO tipi_esame (nome, costo) VALUES('Tipizzazione genomica HLA – DP alta risoluzione', 11);
INSERT INTO tipi_esame (nome, costo) VALUES('Tipizzazione genomica HLA – DQ seq. diretto', 11);
INSERT INTO tipi_esame (nome, costo) VALUES('Tipizzazione genomica HLA – DQ alta risoluzione', 11);
INSERT INTO tipi_esame (nome, costo) VALUES('Tipizzazione genomica HLA – DQB1 bassa risoluzione', 11);
INSERT INTO tipi_esame (nome, costo) VALUES('Tipizzazione genomica HLA – DQB1 alta risoluzione', 11);
INSERT INTO tipi_esame (nome, costo) VALUES('Tipizzazione genomica HLA – DR seq. diretto', 11);
INSERT INTO tipi_esame (nome, costo) VALUES('Tipizzazione genomica HLA – DRB bassa risoluzione', 11);
INSERT INTO tipi_esame (nome, costo) VALUES('Tipizzazione genomica HLA – DRB alta risoluzione', 11);
INSERT INTO tipi_esame (nome, costo) VALUES('Tipizzazione sierologica HLA classe I', 11);
INSERT INTO tipi_esame (nome, costo) VALUES('Tipizzazione sierologica HLA classe II', 11);
INSERT INTO tipi_esame (nome, costo) VALUES('Trombossano B2', 11);
INSERT INTO tipi_esame (nome, costo) VALUES('Viscosità ematica', 11);
INSERT INTO tipi_esame (nome, costo) VALUES('Campylobacter antibiogramma', 11);
INSERT INTO tipi_esame (nome, costo) VALUES('Campylobacter da coltura', 11);
INSERT INTO tipi_esame (nome, costo) VALUES('Campylobacter esame colturale', 11);
INSERT INTO tipi_esame (nome, costo) VALUES('Chlamydie ricerca diretta (EIA)', 11);
INSERT INTO tipi_esame (nome, costo) VALUES('Chlamydie ricerca diretta (IF)', 11);
INSERT INTO tipi_esame (nome, costo) VALUES('Chlamydie ricerca diretta (ibridazione)', 11);
INSERT INTO tipi_esame (nome, costo) VALUES('Miceti anticorpi', 11);
INSERT INTO tipi_esame (nome, costo) VALUES('Miceti lieviti', 11);
INSERT INTO tipi_esame (nome, costo) VALUES('Salmonelle da coltura', 11);
INSERT INTO tipi_esame (nome, costo) VALUES('Shigelle', 11);
INSERT INTO tipi_esame (nome, costo) VALUES('Virus epatite B (HBV) Anticorpi Hbeag', 11);
INSERT INTO tipi_esame (nome, costo) VALUES('Virus epatite B (HBV) Antigeni Hbeag', 11);
INSERT INTO tipi_esame (nome, costo) VALUES('Analisi citogenetica per fragilità cromosomica', 11);
INSERT INTO tipi_esame (nome, costo) VALUES('Analisi citogenetica per ricerca siti fragili', 11);
INSERT INTO tipi_esame (nome, costo) VALUES('Analisi citogenetica per scambi di cromatidi', 11);
INSERT INTO tipi_esame (nome, costo) VALUES('Analisi citogenetica per studio mosaicismo', 11);
INSERT INTO tipi_esame (nome, costo) VALUES('Analisi citogenetica per studio riarrangiamenti', 11);
INSERT INTO tipi_esame (nome, costo) VALUES('Analisi DNA e ibridazione con sonda', 11);
INSERT INTO tipi_esame (nome, costo) VALUES('Analisi DNA per polimorfismo', 11);
INSERT INTO tipi_esame (nome, costo) VALUES('Analisi mutazione del DNA con reazione polimerasica a catena', 11);
INSERT INTO tipi_esame (nome, costo) VALUES('Analisi mutazione del DNA con ibridazione sonde non radiomarcate', 11);
INSERT INTO tipi_esame (nome, costo) VALUES('Analisi mutazione del DNA con ibridazione sonde radiomarcate', 11);
INSERT INTO tipi_esame (nome, costo) VALUES('Analisi mutazione del DNA con reverse dot blot', 11);
INSERT INTO tipi_esame (nome, costo) VALUES('Analisi di polimorfismi', 11);
INSERT INTO tipi_esame (nome, costo) VALUES('Analisi di segmenti di DNA', 11);
INSERT INTO tipi_esame (nome, costo) VALUES('Cariotipo ad alta risoluzione', 11);
INSERT INTO tipi_esame (nome, costo) VALUES('Cariotipo da metafasi di fibroblasti', 11);
INSERT INTO tipi_esame (nome, costo) VALUES('Cariotipo da metafasi linfocitarie', 11);
INSERT INTO tipi_esame (nome, costo) VALUES('Cariotipo da metafasi spontanee di villi corali', 11);
INSERT INTO tipi_esame (nome, costo) VALUES('Cariotipo da metafasi di midollo osseo', 11);
INSERT INTO tipi_esame (nome, costo) VALUES('Colorazione aggiuntiva in bande: Actinomicina D', 11);
INSERT INTO tipi_esame (nome, costo) VALUES('Colorazione aggiuntiva in bande: bandeggio C', 11);
INSERT INTO tipi_esame (nome, costo) VALUES('Colorazione aggiuntiva in bande: bandeggio G', 11);
INSERT INTO tipi_esame (nome, costo) VALUES('Colorazione aggiuntiva in bande: bandeggio G alta ris.', 11);
INSERT INTO tipi_esame (nome, costo) VALUES('Colorazione aggiuntiva in bande: bandeggio NOR', 11);
INSERT INTO tipi_esame (nome, costo) VALUES('Colorazione aggiuntiva in bande: bandeggio Q', 11);
INSERT INTO tipi_esame (nome, costo) VALUES('Colorazione aggiuntiva in bande: bandeggio R', 11);
INSERT INTO tipi_esame (nome, costo) VALUES('Colorazione aggiuntiva in bande: bandeggio T', 11);
INSERT INTO tipi_esame (nome, costo) VALUES('Colorazione aggiuntiva in bande: distamicina A', 11);
INSERT INTO tipi_esame (nome, costo) VALUES('Coltura di amniociti', 11);
INSERT INTO tipi_esame (nome, costo) VALUES('Coltura di cellule o tessuti', 11);
INSERT INTO tipi_esame (nome, costo) VALUES('Coltura di fibroblasti', 11);
INSERT INTO tipi_esame (nome, costo) VALUES('Coltura di linee cellulari stabilizzate con virus', 11);
INSERT INTO tipi_esame (nome, costo) VALUES('Coltura di linee linfocitarie stabilizzate con virus o interleuchina', 11);
INSERT INTO tipi_esame (nome, costo) VALUES('Coltura di linfociti fetali', 11);
INSERT INTO tipi_esame (nome, costo) VALUES('Coltura di linfociti periferici', 11);
INSERT INTO tipi_esame (nome, costo) VALUES('Coltura di materiale abortivo', 11);
INSERT INTO tipi_esame (nome, costo) VALUES('Coltura semisolida di cellule emopoietiche', 11);
INSERT INTO tipi_esame (nome, costo) VALUES('Coltura di villi coriali a breve termine', 11);
INSERT INTO tipi_esame (nome, costo) VALUES('Coltura di cilli coriali', 11);
INSERT INTO tipi_esame (nome, costo) VALUES('Coltura per studio del cromosoma X', 11);
INSERT INTO tipi_esame (nome, costo) VALUES('Conservazione campioni DNA RNA', 11);
INSERT INTO tipi_esame (nome, costo) VALUES('Crioconservazione in azoto liquido di colture cellulari', 11);
INSERT INTO tipi_esame (nome, costo) VALUES('Crioconservazione in azoto liquido di cellule e tessuti', 11);
INSERT INTO tipi_esame (nome, costo) VALUES('Digestione DNA con enzimi', 11);
INSERT INTO tipi_esame (nome, costo) VALUES('Estrazione DNA o RNA', 11);
INSERT INTO tipi_esame (nome, costo) VALUES('Ibridazione con sonda molecolare', 11);
INSERT INTO tipi_esame (nome, costo) VALUES('Ibridazione in SITU (Fish)', 11);
INSERT INTO tipi_esame (nome, costo) VALUES('Ricerca Mutazione (DGGE)', 11);
INSERT INTO tipi_esame (nome, costo) VALUES('Ricerca mutazione (SSCP)', 11);
INSERT INTO tipi_esame (nome, costo) VALUES('Analisi DNA studio citometrico', 11);
